<?xml version="1.0"?>
<package format="2">
  <name>yolo_rviz_markers</name>
  <version>0.0.1</version>
  <description>Publish YOLO detections as RViz markers</description>
  <maintainer email="you@example.com">you</maintainer>
  <license>MIT</license>
  <buildtool_depend>catkin</buildtool_depend>

  <depend>rospy</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>cv_bridge</depend>
  <depend>image_geometry</depend>
  <depend>tf2_ros</depend>
  <build_depend>message_generation</build_depend>
  <depend>message_runtime</depend>
  <!-- optional: if you use a custom YOLO message package (darknet_ros_msgs / yolo_ros_msgs), add it here -->

</package>
