<?xml version="1.0"?>
<package format="2">
  <name>yolo_ros_msgs</name>
  <version>1.0.0</version>
  <description>Bounding-box messages for the optional YOLO ROS bridge.</description>
  <maintainer email="wendy@example.com">wendy</maintainer>
  <license>MIT</license>
  <buildtool_depend>catkin</buildtool_depend>
  <build_depend>std_msgs</build_depend>
  <build_export_depend>std_msgs</build_export_depend>
  <exec_depend>std_msgs</exec_depend>
  <build_depend>message_generation</build_depend>
  <exec_depend>message_runtime</exec_depend>

  <export>

  </export>
</package>
